---
- name: install Epel git and wget
  ansible.builtin.yum:
     name:
        - epel-release
        - git
        - wget
     state: present
  when: ansible_facts['distribution'] == "CentOS"
  #when: ansible_distribution == "CentOS"

- name: download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py

- name: install python-pip
  command: python2.7 /tmp/get-pip.py

- name: Install docker python
  pip:
    name: docker-py

- name: Create a directory if it does not exist
  ansible.builtin.file:
     path: /home/admin/templates
     state: directory
     mode: '0755'

- name: Template index.html file
  ansible.builtin.template:
    src: index.html.j2
    dest: /home/admin/templates/index.html
    mode: '0644'

- name: Create apache a container
  docker_container:
    name: webapp
    image: httpd
    state: started
    ports:
      - "80:80"
    volumes:
      - "/home/admin/templates/index.html:/usr/local/apache2/htdocs/index.html"
